In [2]:
import torch 
import time 
from libs.hij_tensor import get_comb_tensor, spin_flip_rand, uint8_to_bit

In [3]:
x = torch.tensor([0b00001111, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8, device="cpu")
a = []

for i in range(100000):
    x0 = spin_flip_rand(x.clone(), 8, 4, 2023)[1].reshape(1, -1)
    a.append(x0.clone())

unique_sample, idx = torch.unique(torch.cat(a), dim=0, return_counts=True)
print(unique_sample)
print(idx)
print(bin(195))

tensor([[ 15,   0,   0,   0,   0,   0,   0,   0],
        [ 27,   0,   0,   0,   0,   0,   0,   0],
        [ 30,   0,   0,   0,   0,   0,   0,   0],
        [ 39,   0,   0,   0,   0,   0,   0,   0],
        [ 45,   0,   0,   0,   0,   0,   0,   0],
        [ 51,   0,   0,   0,   0,   0,   0,   0],
        [ 54,   0,   0,   0,   0,   0,   0,   0],
        [ 57,   0,   0,   0,   0,   0,   0,   0],
        [ 60,   0,   0,   0,   0,   0,   0,   0],
        [ 75,   0,   0,   0,   0,   0,   0,   0],
        [ 78,   0,   0,   0,   0,   0,   0,   0],
        [ 90,   0,   0,   0,   0,   0,   0,   0],
        [ 99,   0,   0,   0,   0,   0,   0,   0],
        [102,   0,   0,   0,   0,   0,   0,   0],
        [105,   0,   0,   0,   0,   0,   0,   0],
        [108,   0,   0,   0,   0,   0,   0,   0],
        [135,   0,   0,   0,   0,   0,   0,   0],
        [141,   0,   0,   0,   0,   0,   0,   0],
        [147,   0,   0,   0,   0,   0,   0,   0],
        [150,   0,   0,   0,   0,   0,   0,   0],


In [4]:
x1 = get_comb_tensor(x, 8, 4, True)
print(x1)

tensor([[ 15,   0,   0,   0,   0,   0,   0,   0],
        [ 30,   0,   0,   0,   0,   0,   0,   0],
        [ 78,   0,   0,   0,   0,   0,   0,   0],
        [ 45,   0,   0,   0,   0,   0,   0,   0],
        [141,   0,   0,   0,   0,   0,   0,   0],
        [ 27,   0,   0,   0,   0,   0,   0,   0],
        [ 75,   0,   0,   0,   0,   0,   0,   0],
        [ 39,   0,   0,   0,   0,   0,   0,   0],
        [135,   0,   0,   0,   0,   0,   0,   0],
        [ 60,   0,   0,   0,   0,   0,   0,   0],
        [156,   0,   0,   0,   0,   0,   0,   0],
        [108,   0,   0,   0,   0,   0,   0,   0],
        [204,   0,   0,   0,   0,   0,   0,   0],
        [ 90,   0,   0,   0,   0,   0,   0,   0],
        [ 54,   0,   0,   0,   0,   0,   0,   0],
        [150,   0,   0,   0,   0,   0,   0,   0],
        [102,   0,   0,   0,   0,   0,   0,   0],
        [198,   0,   0,   0,   0,   0,   0,   0],
        [ 57,   0,   0,   0,   0,   0,   0,   0],
        [153,   0,   0,   0,   0,   0,   0,   0],


In [4]:
x = torch.tensor([0b00001111, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8, device="cpu")
a = []

for i in range(100000):
    x0 = spin_flip_rand(x, 8, 4, 2023)[1].reshape(1, -1)
    a.append(x0.clone())

unique_sample, idx = torch.unique(torch.cat(a), dim=0, return_counts=True)
print(unique_sample)
print(idx)

tensor([[ 15,   0,   0,   0,   0,   0,   0,   0],
        [ 27,   0,   0,   0,   0,   0,   0,   0],
        [ 30,   0,   0,   0,   0,   0,   0,   0],
        [ 39,   0,   0,   0,   0,   0,   0,   0],
        [ 45,   0,   0,   0,   0,   0,   0,   0],
        [ 51,   0,   0,   0,   0,   0,   0,   0],
        [ 54,   0,   0,   0,   0,   0,   0,   0],
        [ 57,   0,   0,   0,   0,   0,   0,   0],
        [ 60,   0,   0,   0,   0,   0,   0,   0],
        [ 75,   0,   0,   0,   0,   0,   0,   0],
        [ 78,   0,   0,   0,   0,   0,   0,   0],
        [ 90,   0,   0,   0,   0,   0,   0,   0],
        [ 99,   0,   0,   0,   0,   0,   0,   0],
        [102,   0,   0,   0,   0,   0,   0,   0],
        [105,   0,   0,   0,   0,   0,   0,   0],
        [108,   0,   0,   0,   0,   0,   0,   0],
        [114,   0,   0,   0,   0,   0,   0,   0],
        [120,   0,   0,   0,   0,   0,   0,   0],
        [135,   0,   0,   0,   0,   0,   0,   0],
        [141,   0,   0,   0,   0,   0,   0,   0],
